### ISSUE TITLE
[Feature] Better calculation of air density

### ISSUE THREAD

**Issue by JKamue** [JKamue/SpaceFlight#10]
**Is your feature request related to a problem? Please describe.**
At the moment the density of air is calculated in steps. If the altitude is between x and y it will get a fixed value.
That leads to kind of a staircase like shape which results in big steps between Drag values when the altitude reaches the next step.
```c#
var densityAtAltitude = new Dictionary<Func<double, bool>, double>
  {
    { x => x < 0, 0},
    { x => x < 1000, 1.225},
    { x => x < 2000, 1.112},
    { x => x < 3000, 1.007},
    { x => x < 4000, 0.9093},
    ...
  };
```
[Link to code](https://github.com/JKamue/SpaceFlight/blob/master/SpaceFlight/Physics/Calculator/AtmosphereCalculator.cs)

**Describe the solution you'd like**
A function that smoothly outputs realistic values for altitudes up to 90km altitude.
sidered.

**Additional context**
@PhilHawk03 already mentioned that making a function out of [these points](https://www.engineeringtoolbox.com/standard-atmosphere-d_604.html) could be one way of solving this problem.

**Comment by PhilHawk03** [comment]
Also, ich habe alle daten ausgewertet, die Funktion, die am nächsten kommt ist tatsächlich 1,4477 * 0,9999^x
Vorschlag für einen Code würde so aussehen: 
 height = x
 if 0<height <100000 {
 p = 1,4477*0,9999^x
}
else 
 p= 0

**Comment by PhilHawk03** [comment]
Neue Idee: Wir benutzen 3 Funktionen, um die Luftdichte zu beschreiben. 
Die Funktion f(x) = 1,2526 * 0,9999^x beschreibt die Luftdichte zwischen 0 und 10000 m. 
Von 10000m bis 30000m beschreibt die Funktion: f(x) = 1.9971 * 0,9998^x die Luftdichte. 
Über 30000m bis 80000m können wir: 0,9786 * 0.9999^x benutzen.
