### ISSUE TITLE
[Documentation] Add list of rockets to documentation

### ISSUE THREAD

**Issue by JKamue** [JKamue/SpaceFlight#12]
We should add a list of all playable rockets as well as upcoming rockets.
I would recommend to create a small wiki.
Then we could list each rocket as well as their properties (weight, thrust, etc)

**Comment by PhilHawk03** [comment]
Kann ich auch machen,  musst mir nur sagen welches Wiki-Tool ich nutzen soll

**Comment by JKamue** [comment]
Going to close this for now since all rockets are documented at the moment. Might be reopened in the future
