### ISSUE TITLE
[Documentation] Explain how to make own rockets or levels

### ISSUE THREAD

**Issue by JKamue** [JKamue/SpaceFlight#14]
Add a small paragraph or wiki page explaining extensions and modifications of the Data json files:

- Own level creation
- Rocket modding
- Own rocket creation

Also develope a tool to make drawing rockets easier.

**Comment by PhilHawk03** [comment]
Kann ich später machen, werde erstmal das aktuelle Tool verlinken

**Comment by JKamue** [comment]
Started to develope a new improved tool: https://jkamue.de/space/

**Comment by JKamue** [comment]
Added guide explaining how to make own rockets / levels and change existing rockets / levels here: https://github.com/JKamue/SpaceFlight/wiki/Modding/_edit
