### ISSUE TITLE
[Bug] Crash when you close the InfoScreen window

### ISSUE THREAD

**Issue by Nalsai** [JKamue/SpaceFlight#23]
**Describe the bug**
When you close the InfoScreen window the game crashes

**To Reproduce**
1. Open SpaceFlight.exe
2. Close InfoScreen window

**Expected behavior**
The game doesn't crash

**Version**
Probably all versions, latest commit: 1be2128

**Additional context**
When you are debugging in Visual Studio this can prevent you from stopping the game because the main window stays on top and covers the stop button. Then you have to use the task manager.

**Comment by JKamue** [comment]
Yeah I knew this bug but forgot to document it. I usally move visual studio to the second screen and then stop the program there. Do you want to fix this bug or do you want me to take a look into it?

**Comment by JKamue** [comment]
Take a look at 65162c6c8f482e6eee04a320ad6a1d51bd7d4b73, I hope that I fixed the bug you described!
Thank you for reporting it!
