### ISSUE TITLE
[Feature] Show acceleration in g

### ISSUE THREAD

**Issue by JKamue** [JKamue/SpaceFlight#26]
**Is your feature request related to a problem? Please describe.**
Show the acceleration in g (https://en.wikipedia.org/wiki/Standard_gravity) on the InfoScreen

**Describe the solution you'd like**
Maybe round the acceleration to less digits and make space for a small (1.23g) in the back.
Maybe add a seperate menu point.

**Comment by PhilHawk03** [comment]
Ich würde eher mit exakten Werten am ANfang rechnen und dann hinterher auf zwei Dezimalstellen runden

**Comment by JKamue** [comment]
Nein ich meinte die Anzeige der Beschleunigung, accelerstion wird glaube ich mit 4 Nachkommastellen angezeigt,wenn wir nur 2 anzeigen ist Platz für die X G Anzeige mit 1 oder 2 Nachkommastellen
