### ISSUE TITLE
[Enhancement] Ability to have all windows go to the background

### ISSUE THREAD

**Issue by Nalsai** [JKamue/SpaceFlight#42]
**Is your feature request related to a problem? Please describe.**
The game windows always stay on top which means that you can't see any other application behind it. This can be problematic when you need to open another application and see it's window without closing the game or you are unable to close the game.

**Describe the solution you'd like**
All windows should be able to go to the background.
For ease of use all game windows should be opened and minimized together.

**Additional context**
Sebastian Fay had a problem where he was unable to close the game window while debugging and he couldn't access the task manager because the window of the game was in front of it.

**Comment by JKamue** [comment]
I am experiencing some strange bug with this coomit. I cannot access the controls, here is a video https://youtu.be/3aBXlCWm3W0
