### ISSUE TITLE
[Feature][Orbit Screen Simulator]

### ISSUE THREAD

**Issue by PhilHawk03** [JKamue/SpaceFlight#52]
Simualate what would happen on the Orbit Screen if the vehicle was accelaerated or decellerated. Do this by Simulating the "new" orbital trajectory just as the current one and show both to the Orbit Screen. If there are any questions please contact PhilHawk03.

**Comment by JKamue** [comment]
Just an additional orbit prediction in orange calculating the orbit if thrust is continued?

**Comment by PhilHawk03** [comment]
kind of... 
I menat that one can click a point on the actual trajectory, where you can adjust the delta V by clicking + or -. The rest is the same as you said

**Comment by PhilHawk03** [comment]
Great work by Jkamue
