### ISSUE TITLE
[Bug] Sometimes the close buttons of the info screen and the orbit screen don't work

### ISSUE THREAD

**Issue by Nalsai** [JKamue/SpaceFlight#57]
**Describe the bug**
Sometimes the close buttons of the info screen and the orbit screen don't work. Nothing happens when you click on them. Sometime even all close buttons get disabled after that and the entire game doesn't respond to any input.

**To Reproduce**
1. Open Game
2. Click on the close button of the info screen

**Expected behavior**
The game should exit

**Version**
since commit 5a5f73a; newest commit 8fc79a5

**Comment by JKamue** [comment]
Seems to have been fixed by the fix for #42 as well
