### ISSUE TITLE
[Enhancement] add .gitattributes file

### ISSUE THREAD

**Issue by Nalsai** [JKamue/SpaceFlight#65]
**Is your feature request related to a problem? Please describe.**
When @simselchen commits something the line endings get changed.

**Describe the solution you'd like**
Add a .gitattributes file to ensures consistent behavior for all users, regardless of their Git settings and environment.

**Describe alternatives you've considered**
@simselchen should fix his config

**Comment by JKamue** [comment]
49c9102a087818b6d0f2da33e5c214dc013bef1c
c78a36763556382dd355a4a9288babe44836fb75
ad1e6d39cd6c3796f5d9cdece5abe3702cd8dc39
